version: '3.8'

services:
  app:
    image: 515966527734.dkr.ecr.ap-northeast-2.amazonaws.com/ggm-server:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7.2
    container_name: ggm-redis
    ports:
      - "6379:6379"
    restart: always
