spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DEV_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:

  data:
    redis:
      host: localhost
      port: 6379

  s3:
    directory: dev
